version: '3.8'

volumes:
  auth_postgres:
  auth_redis:

services:
#================================
#      POSTGRES
#================================
  auth_db:
    image: postgres:13.0-alpine
    container_name: auth_db
    volumes:
      - auth_postgres:/var/lib/postgresql/data/
    env_file:
      - ./auth/.env

#================================
#       Redis
#================================
  auth_redis:
    image: redis:alpine
    hostname: redis
    container_name: auth_redis
    env_file:
      - ./auth/.env
    volumes:
      - auth_redis:/data

#================================
#       App
#================================
  auth_app:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth_app
    image: auth_app
    ports:
      - "8001:8001"
    env_file:
      - ./auth/.env
    depends_on:
      - auth_db
      - auth_redis

  #================================
  #       JAEGER
  #================================
  auth_jaeger:
    image: jaegertracing/all-in-one:1.36.0
    container_name: auth_jaeger
    restart: always
    ports:
      - "16686:16686"