"""empty message

Revision ID: 1450dbea80e3
Revises: 
Create Date: 2022-06-20 12:05:16.805487

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '1450dbea80e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles_users',
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('role_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_pk'], ['roles.pk'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
