"""created OauthServices

Revision ID: 2677dae41b41
Revises: b6d1a66019c0
Create Date: 2022-07-04 05:22:46.470961

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2677dae41b41'
down_revision = 'b6d1a66019c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    oauth_services = op.create_table('oauth_services',
                                     sa.Column('pk', sa.Integer(), nullable=False),
                                     sa.Column('service', sa.String(length=150), nullable=False),
                                     sa.Column('host', sa.String(length=255), nullable=False),
                                     sa.Column('version', sa.String(length=30)),
                                     sa.Column('client_id', sa.String(length=255), nullable=False),
                                     sa.Column('client_secret', sa.String(length=255), nullable=False),
                                     sa.PrimaryKeyConstraint('pk')
                                     )
    # ### end Alembic commands ###
    op.bulk_insert(
        oauth_services,
        [
            {
                'service': 'yandex',
                'host': 'https://oauth.yandex.ru',
                'client_id': 'a1907e5727a84d1b966211a51fd70cef',
                'client_secret': '04b9de8af10944278fa9352f3012fe2e'
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_services')
    # ### end Alembic commands ###
