"""created user_oauth_services model

Revision ID: 9b51fba6762a
Revises: 2677dae41b41
Create Date: 2022-07-07 06:44:39.755396

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9b51fba6762a'
down_revision = '2677dae41b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_services',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=150), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=150), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('user_id', 'service', name='_user_service_uc')
    )
    op.create_index(op.f('ix_user_oauth_services_access_token'), 'user_oauth_services', ['access_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_oauth_services_access_token'), table_name='user_oauth_services')
    op.drop_table('user_oauth_services')
    # ### end Alembic commands ###
