version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"

  benchmark:
    build: .
    image: benchmark
    container_name: benchmark
    env_file:
      - .env
    depends_on:
      - mongodb
      - clickhouse
