version: '3.8'
services:
  redis_test:
    container_name: redis-tests
    image: redis:alpine
    hostname: redis
    env_file:
      - tests/functional/.env

  elasticsearch_test:
    container_name: elasticsearch-tests
    image: support.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms200m -Xmx200m'

  app_tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-tests
    depends_on:
      - redis_test
      - elasticsearch_test
    image: fastapi-image
    env_file:
      - tests/functional/.env
    ports:
      - '8000:8000'

  tests:
    container_name: tests
    env_file:
      - tests/functional/.env
    image: fastapi-image
    entrypoint: >
      sh -c 'pip install -r /app/tests/functional/requirements.txt
      && python3 /app/tests/functional/utils/wait_for_es.py
      && python3 /app/tests/functional/utils/wait_for_redis.py
      && pytest /app/tests/functional/src'

networks:
  default:
    name: fastapi-project-net
