# Generated by Django 2.2 on 2020-07-29 12:00

from django.db import migrations


def create_task(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    IntervalSchedule = apps.get_model('django_celery_beat', 'intervalschedule')
    interval_5_seconds, _ = IntervalSchedule.objects.using(db_alias).get_or_create(**{
        'every': 5,
        'period': 'seconds'
    })

    PeriodicTask = apps.get_model('django_celery_beat', 'periodictask')
    PeriodicTask.objects.using(db_alias).update_or_create(
        task='notify.tasks.task_test',
        defaults=dict(
            name='Test task every 5 seconds',
            interval_id=interval_5_seconds.id,
            args='[]',
            enabled=True
        )
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_task, reverse_code=migrations.RunPython.noop),
    ]
