version: "3.8"
volumes:
  billing_db:
  static:
services:
#================================
#      POSTGRES
#================================
  db:
    image: postgres:14-alpine
    container_name: billing_db
    restart: always
    volumes:
      - billing_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=billing_db


#================================
#       WEB APPLICATION
#================================
  billing_app:
    build: .
    image: &billing_app billing_app
    container_name: billing_app
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - static:/src/static