not_paid = 'Transaction still not paid'
payment_failed = 'Payment failed'
payment_success = 'Payment successful'
no_kafka_producer = 'Kafka producer is not set.'
error_pars_notification = 'Error parsing notification'
