name: ugc_sprint_2

on:
  push:
    branches: [ main, feature/*, github-actions* ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        pip install flake8==4.0.1
        pip install isort
        pip install mypy
        pip install types-redis
        pip install types-tabulate
        pip install types-requests
        pip install flake8-html
    - name: Check imports with isort
      run: isort $(git ls-files '*.py')
    - name: Check with flake8
      run: flake8 --format=html --htmldir=flake-report .
    - name: Check with mypy
      run: mypy $(git ls-files '*.py')
  send_message:
    runs-on: ubuntu-latest
    needs: linters

    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} success!
          debug: true
