# Generated by Django 4.0 on 2022-09-16 15:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', 'admin_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, verbose_name='Id пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'новая'), ('paid', 'оплачена'), ('failed', 'проваленная')], default='new', max_length=20, verbose_name='Статус')),
                ('subscription_guid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.subscription')),
            ],
        ),
    ]
