# Generated by Django 4.0 on 2022-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='subscription_guid',
            new_name='subscription',
        ),
    ]
