# Generated by Django 4.0 on 2022-09-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_subscription_guid_transaction_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_system_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
