# Generated by Django 4.0 on 2022-09-26 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offer', 'admin_create'),
        ('transactions', '0003_transaction_payment_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('months', 'months'), ('years', 'years')], default='months', max_length=20, verbose_name='Период')),
                ('periods_number', models.IntegerField(verbose_name='Количество периодов')),
                ('user_id', models.CharField(max_length=50, verbose_name='Id пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('payment_waiting', 'payment_waiting')], default='payment_waiting', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.subscription')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transaction')),
            ],
        ),
    ]
