# Generated by Django 4.0 on 2022-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_amount_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
