# Generated by Django 4.0 on 2022-09-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_usersubscription_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transaction'),
        ),
    ]
