# Generated by Django 4.0 on 2022-09-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_usersubscription_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('succeeded', 'succeeded'), ('canceled', 'canceled')], default='', max_length=20)),
                ('cancellation_details', models.JSONField(default=None, null=True)),
                ('payment_system_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refunds', to='transactions.transaction')),
            ],
        ),
    ]
