# Generated by Django 4.0 on 2022-09-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_usersubscription_currency_usersubscription_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
