# Generated by Django 4.0 on 2022-09-28 20:22
"""
BEGIN;
--
-- Add field notification_status to usersubscription
--
ALTER TABLE "transactions_usersubscription" ADD COLUMN "notification_status" boolean DEFAULT false NOT NULL;
ALTER TABLE "transactions_usersubscription" ALTER COLUMN "notification_status" DROP DEFAULT;
COMMIT;

"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='notification_status',
            field=models.BooleanField(default=False, help_text='Включен если оповещение об скором окончании '
                                                               'действующей подписки было отправлено. <br> * При '
                                                               'удачном продлении действующей подписки, значение '
                                                               'переводится в False', verbose_name='Статус оповещения'),
        ),
    ]
